### PR TITLE
Fix shortcut nav

### LINKED ISSUE #796: Fix handling of follow/unfollow in Shortcut Nav

### LINKED ISSUE #799: Cursor doesn't move to proper pill in hotspot nav
if you tap on a hotspot from the list, the cursor doesn't jump to the proper pill in the shortcut nav

### PR DESCRIPTION
**Pull request by matthewcarlreetz**
Fix scroll offsets when follow/unfollow hotspot.
Closes #796

Fix pill not snapping when selecting from listview or search.
Closes #799

### CODE REVIEW

File: src/features/hotspots/root/ShortcutNav.tsx [hunk 1]
```diff
@@ -216,58 +220,90 @@ const ShortcutNav = ({
...
+
+  useEffect(() => {
     if (prevFollowed && followedHotspots.length !== prevFollowed.length) {
+      // remove this item from the size list
+      if (internalItem.index >= GLOBAL_OPTS.length) {
+        let addressToRemove = ''
+        if (propsItem) {
+          addressToRemove = getItemId(propsItem)
+        }
+        sizes[addressToRemove] = null
```
Comment (allenan) [inline src/features/hotspots/root/ShortcutNav.tsx:280]: so if `!propsItem`, then this is going to execute as `sizes[''] = null`. Is that the desired outcome?

Comment (matthewcarlreetz) [reply src/features/hotspots/root/ShortcutNav.tsx:280]: No, good catch. I removed the else block I had and didn't adjust this.

**Review by allenan — APPROVED** [review]
the rest looks good to me codewise
