### PR TITLE
Fix disco timer when app put in background.

### LINKED ISSUE #603: Disco mode session time paused in app when it goes to sleep
when the phone goes to sleep during an active disco session, the timer pauses, leading users to believe a session can last longer than 5 minutes.

the timer picks up again when the app is in the foreground - this isn't indicative of what happens on the wallet-api side.

### PR DESCRIPTION
**Pull request by matthewcarlreetz**
Closes #603

### CODE REVIEW

File: src/features/hotspots/settings/discovery/useDiscoveryPoll.ts [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+
+type Props = { viewState: ViewState; hotspot: Hotspot }
+
+const unixTime = (dateStr?: string) => {
+  const insertDate = dateStr ? new Date(dateStr) : null
+  if (!insertDate) return 0
+
+  return getUnixTime(insertDate)
+}
+const useDiscoveryPoll = ({ viewState, hotspot }: Props) => {
```
Comment (tyler-whitman) [inline src/features/hotspots/settings/discovery/useDiscoveryPoll.ts:19]: I have used https://github.com/ocetnik/react-native-background-timer in the past too for background timers. But looks like you got it working without needing it

**Review by tyler-whitman — APPROVED** [review]
Looks good, we could use the background timer library or leave as.

File: src/features/hotspots/settings/discovery/useDiscoveryPoll.ts (hunk 1 above)
Comment (matthewcarlreetz) [reply src/features/hotspots/settings/discovery/useDiscoveryPoll.ts:19]: Nice. I'll keep that in mind for future stuff.
