### PR TITLE
Hide content pill when one item. Fix auto-scroll.

### LINKED ISSUE #668: Remove Hotspot Pill when only one hotspot
Hide the content pill when there's only one hotspot in the hex.

### PR DESCRIPTION
**Pull request by matthewcarlreetz**
closes #668

### CODE REVIEW

File: src/components/ContentPill.tsx [hunk 1]
```diff
@@ -141,7 +138,7 @@ const ContentPill = ({
     const length = flatListData?.length || 0
     return {
       length,
-      offset: length * index,
+      offset: (index - 1) * ITEM_SIZE,
```
Comment (matthewcarlreetz) [inline src/components/ContentPill.tsx:141]: @tyler-whitman I'm not sure what the desired effect here is, but there was a bug when clicking on indexes beyond what could fit on the screen.

Comment (tyler-whitman) [reply src/components/ContentPill.tsx:141]: Ah ok, this looks good. It was just to make sure the item selected is in view when you choose a hotspot from the list that is further down in the pill than the first page. Its working well for me still

**Review by tyler-whitman — APPROVED** [review]
