### PR TITLE
Fix/misc fixes

### LINKED ISSUE #122: Design Tweaks: Wallet Page
Details are in Figma > Hotspot Tab (at the top), also pasted below.

image
image
image

### LINKED ISSUE #188: Fix gesture handling on charts in listview
when you pan down in the hotspot details list view, the charts often steal your gesture. We should tune that gesture handler so that it's not as sensitive to vertical gestures.

### PR DESCRIPTION
**Pull request by allenan**
resolves #122 
- sets wallet button icons to use a fixed height rather than width so that the icons will render the same size
- fixes security token amount display

resolves #188 
- tune the chart pan responder to reject gestures that are too vertical, this allows you to swipe down the hotspot charts view without having your gesture stolen by the chart

this isn't 100% perfect, you can still get a chart stuck in an active state if you manage to trigger the scroll gesture while the chart is active. But it doesn't impact the usability because you can still scroll and it's easy to get the chart unstuck. I think we could do something fancy with nested gesture-handlers and `waitFor`, but this is an improvement over the current situation.

### CODE REVIEW

File: src/features/wallet/root/BalanceCard/BalanceCard.tsx [hunk 1]
```diff
@@ -83,7 +83,11 @@ const BalanceCard = ({ onReceivePress, onSendPress }: Props) => {
           />
           <CurrencyBadge
             variant="hst"
-            amount={account?.secBalance?.integerBalance || 0}
+            amount={
```
Comment (tyler-whitman) [inline src/features/wallet/root/BalanceCard/BalanceCard.tsx:86]: Not sure what was wrong here, but maybe https://github.com/helium/helium-js/pull/146 would help too

**Review by tyler-whitman — APPROVED** [review]
Looks good

File: src/features/wallet/root/BalanceCard/BalanceCard.tsx (hunk 1 above)
Comment (allenan) [reply src/features/wallet/root/BalanceCard/BalanceCard.tsx]: basically we needed the float balance instead of the integer balance. I just updated to a better way to do that
