### PR TITLE
Fix activity list animation points

### LINKED ISSUE #385: Tidy blank state & remove HST/DC markers if 'nil' qty
Screenshot 2021-03-15 at 16 19 42

### PR DESCRIPTION
**Pull request by matthewcarlreetz**
Closes #385

### CODE REVIEW

File: src/features/wallet/root/ActivityCard/ActivityCard.tsx [hunk 1]
```diff
@@ -39,6 +39,7 @@ const ActivityCard = forwardRef((props: Props, ref: Ref<BottomSheet>) => {
     showSkeleton,
   } = props
   const { dragMax, dragMid, dragMin } = animationPoints
+  console.log({ dragMax })
```
Comment (tyler-whitman) [inline src/features/wallet/root/ActivityCard/ActivityCard.tsx:42]: We should remove this log

**Review by tyler-whitman — CHANGES_REQUESTED** [review]
Tested on iPhone 11 and its working perfectly.

**Review by tyler-whitman — APPROVED** [review]
