### PR TITLE
Handle onboarding service unavailable when onboarding hotspot.

### LINKED ISSUE #722: Onboarding Server Error check
The onboarding server went down today, but folks were shown error messages that their Hotspot doesn't exist on the Onboarding server (incorrect).
image
image

We should have a check to see if the onboarding server is running, and if it's not, display a different error message:

Onboarding Error

The Onboarding Server is temporarily unavailable and users won't be able to add Hotspots at this time. 
Check for updates on status.helium.com and try again later.

### PR DESCRIPTION
**Pull request by matthewcarlreetz**
closes #722

### CODE REVIEW

File: src/features/hotspots/setup/OnboardingErrorScreen.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ const OnboardingErrorScreen = () => {
 
         <Text variant="h1">{t('hotspot_setup.onboarding_error.title')}</Text>
         <Text variant="body1" marginVertical="l">
-          {t('hotspot_setup.onboarding_error.subtitle')}
+          {t(`hotspot_setup.onboarding_error.subtitle.${connectStatus}`)}
```
Comment (allenan) [inline src/features/hotspots/setup/OnboardingErrorScreen.tsx:32]: is there a fallback message if there's no i18n string defined for the `HotspotConnectStatus`?

File: src/utils/useHotspot.ts [hunk 2]
```diff
@@ -186,8 +187,16 @@ const useHotspot = () => {
     await updateHotspotStatus(payload?.hotspot)
 
     if (!payload?.onboardingRecord?.onboardingKey) {
-      Logger.error(new Error('Hotspot connect failed: no onboardingKey'))
-      return handleConnectStatus('no_onboarding_key')
+      let err: HotspotConnectStatus = 'service_unavailable'
+      if (payload?.onboardingRecord?.code === 404) {
```
Comment (allenan) [inline src/utils/useHotspot.ts:191]: does `no_onboarding_key` still occur? I see previously this returned `handleConnectStatus('no_onboarding_key')`, but now I see it returning `invalid_onboarding_address`. Additionally the two subtitle options in the i18n file are `no_onboarding_key` and `service_unavailable` but I see `invalid_onboarding_address` and `service_unavailable` being returned from here

File: src/features/hotspots/setup/OnboardingErrorScreen.tsx (hunk 1 above)
Comment (matthewcarlreetz) [reply src/features/hotspots/setup/OnboardingErrorScreen.tsx]: There isn't, but there should be.

**Review by allenan — APPROVED** [review]
