### PR TITLE
Bugfix/278 android wifi

### LINKED ISSUE #278: android: Unable to set wi-fi for a Hotspot
Android only, happens when onboarding a NEW hotspot, and updating the wi-fi of an EXISTING hotspot.
Video here: https://discord.com/channels/404106811252408320/733699201887764511/813598221254656010
Steps to reproduce (new hotspot):
1. enter add hotspot flow
2. connect to Hotspot over bluetooth
3. select a wi-fi  network to connect to, enter password, press next
4. error "something went wrong"

Steps to reproduce (existing hotspot):
1. go to hotspot, tap settings
2. connect to hotspot over bluetooth
3. select a wi-fi network to connect to, app does not respond
expected results: app should pop up a modal asking to forget network, like iOS does.
IMG_1E23C3B3C7E4-1

This is not reproducible on iOS.

### PR DESCRIPTION
**Pull request by matthewcarlreetz**
Closes #278

### CODE REVIEW

File: src/utils/useHotspot.ts [hunk 1]
```diff
@@ -239,30 +240,44 @@ const useHotspot = () => {
...
+    ) => {
       if (error) {
         Logger.error(error)
-        subscription?.remove()
-        callback?.('error')
       }
 
-      if (!c?.value) return
+      cb?.(type)
+      cb = null // prevent multiple callbacks. Android throws an error when the subscription is removed.
```
Comment (allenan) [inline src/utils/useHotspot.ts:253]: wtf android

**Review by allenan — APPROVED** [review]
🚢

**Review by tyler-whitman — APPROVED** [review]
