### PR TITLE
fix lag when pressing update hotspot button

### LINKED ISSUE #1093: Remove API / owner look up when pairing with a Hotspot
The app currently looks up (via API) who the owner of a Hotspot is before pairing. This was carried over from onboarding a Hotspot (to see if the Hotspot has an owner or not) and reused in this pairing flow. 

In any normal circumstance, this API check would not be a roadblock to pairing with a Hotspot, but during the outage, it was impossible to pair with a Hotspot, which exposed the API check. 

We don't think this api check is necessary and should be removed.

### PR DESCRIPTION
**Pull request by tyler-whitman**
We are checking for existing pending transactions when tapping the update hotspot item in hotspot settings which is taking a long time to complete now that the API is slow. 

I moved the check to happen when you actually try to submit the transaction instead. Allowing more time for a current pending to clear and also flows better with the UI.

closes #1093

### CODE REVIEW

File: src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx [hunk 1]
```diff
@@ -183,8 +190,35 @@ const UpdateHotspotConfig = ({ onClose, onCloseSettings, hotspot }: Props) => {
...
+          pendingTxn.txn.gateway === hotspot?.address
+        )
+      })
+    } catch (e) {}
+    return false
+  }, [dispatch, hotspot?.address])
+
   const onSubmit = async () => {
     setLoading(true)
+    const hasExistingPendingTxn = await hasPendingTransaction()
```
Comment (matthewcarlreetz) [inline src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx:216]: should we do this on mount instead? That way if the API is slow it has more time to load.

File: src/utils/useHotspot.ts [hunk 2]
```diff
@@ -129,6 +129,7 @@ const useHotspot = () => {
 
   const connectAndConfigHotspot = async (
     hotspotDevice: Device,
+    isDiagnostics?: boolean,
```
Comment (matthewcarlreetz) [inline src/utils/useHotspot.ts:132]: could we use an options object here? That way when viewing a function call the intent is more clear
`connectAndConfigHotspot(hotspot, { isDiagnostics: true} )`

**Review by matthewcarlreetz — APPROVED** [review]

File: src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx (hunk 1 above)
Comment (tyler-whitman) [reply src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx:216]: I feel like it would be weird to have it just pop up though. I think the flow is better so that it can wait until the last moment to check in case the other one clears.

File: src/utils/useHotspot.ts (hunk 2 above)
Comment (tyler-whitman) [reply src/utils/useHotspot.ts:132]: Yeah, ill update it

File: src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx (hunk 1 above)
Comment (tyler-whitman) [reply src/features/hotspots/settings/updateHotspot/UpdateHotspotConfig.tsx:216]: It has a nice loading animation in the button, so you at least know its loading
