### PR TITLE
fix send forum corners

### LINKED ISSUE #608: missing rounded corners when scanning payment_v2 transactions
IMG_752757072907-1

### PR DESCRIPTION
**Pull request by tyler-whitman**
closes #608

### CODE REVIEW

File: src/components/InputField.tsx [hunk 1]
```diff
@@ -18,6 +18,8 @@ type Props = {
   defaultValue?: string
   value?: string
   numberOfLines?: number
+  bottom?: boolean
```
Comment (matthewcarlreetz) [inline src/components/InputField.tsx:21]: At a glance what `top` and `bottom` means is unclear to me. Maybe we could call them `topRadius` and `bottomRadius`? Another pattern I've been using for rounding corners is `isFirst` and `isLast`.

**Review by matthewcarlreetz — APPROVED** [review]

File: src/components/InputField.tsx (hunk 1 above)
Comment (tyler-whitman) [reply src/components/InputField.tsx:21]: Good point, I like isFirst, isLast. Let me update
