### PR TITLE
fix chart pan gesture

### LINKED ISSUE #407: Hotspot detail charts pan gesture no longer working
The pan gesture for the hotspot details is no longer working, it stops sliding after one bar.

### PR DESCRIPTION
**Pull request by tyler-whitman**
closes #407 

- fixes the chart pan gesture when inside a bottom sheet
- updates reanimated to the official v2.0.0 build
- updates @gorhom/bottom-sheet to v3.4.1
- removes some unused packages

### CODE REVIEW

File: src/components/BarChart/Chart.tsx [hunk 1]
```diff
@@ -134,78 +138,73 @@ const BarChart = ({
...
-              rx={barWidth / 2}
-              width={barWidth}
-              height={barHeight(v?.up)}
-              fill={upColor || greenBright}
-              opacity={!focusedBar || focusedBar?.id === v.id ? 1 : 0.4}
-            />
-
-            {hasDownBars && (
+      <Animated.View
+        style={{
```
Comment (matthewcarlreetz) [inline src/components/BarChart/Chart.tsx:156]: Could probably cleanup this inline style.

**Review by matthewcarlreetz — APPROVED** [review]
It seems to work really well on ios and Android. There are some inline styles/objects/calcs that could be cleaned up, but I'll leave that up to you. I did notice a little oddness with the data that is likely unrelated to this PR

IMG_6949

File: src/components/BarChart/Chart.tsx (hunk 1 above)
Comment (tyler-whitman) [reply src/components/BarChart/Chart.tsx:156]: Moved it out and use memo
