### PR TITLE
Fix wifi forget and improve ux.

### LINKED ISSUE #310: Unable to update Wi-Fi for a Hotspot
Several users in Discord are reporting they're unable to update the Wi-Fi of their Hotspot.

Steps to repro:
1. pair with the hotspot
2. tap update wi-fi
3. tap the new network you want to connect to
4. see popup "forget wi-fi"
5. tap "forget" to confirm
6. dialog dismisses, not offered to enter new network's password. if you try to select the new network again, you're stuck in the same loop.
effectively, the wi-fi network is never "forgotten".

User 1.
Iphone 10x, RAK v1 Hotspot

User 2
iPhone 8, RAK v1 Hotspot

Coco's testing notes:
Tested on Android and iOS on RAK Hotspot (EU). I was able to proceed past step 5 but if you reconnect to the hotspot, it displays the old network I had tried to forget.

### PR DESCRIPTION
**Pull request by matthewcarlreetz**
Closes #310 

- Fixes not being able to change the wifi network when you're not configured to your configured network.
- Fixes some UX painpoints

### CODE REVIEW

File: src/features/hotspots/details/HotspotDetails.tsx [hunk 1]
```diff
@@ -120,7 +120,7 @@ const HotspotDetails = ({ hotspot }: { hotspot?: Hotspot }) => {
   if (!hotspot) return null
 
   return (
-    <BottomSheetScrollView>
+    <BottomSheetScrollView keyboardShouldPersistTaps="always">
```
Comment (tyler-whitman) [inline src/features/hotspots/details/HotspotDetails.tsx:123]: Ah was the keyboard disappearing when they tried to type the password?

File: src/features/hotspots/settings/WifiSettings.tsx [hunk 2]
```diff
@@ -34,45 +34,48 @@ const WifiSettings = ({ onNetworkSelected }: Props) => {
...
     async (nextWifi: string) => {
-      if (wifi || configuredNetworks.length) {
-        const wifiName = wifi || configuredNetworks[0]
-        const decision = await showOKCancelAlert({
-          titleKey: 'hotspot_setup.disconnect_dialog.title',
-          messageKey: 'hotspot_setup.disconnect_dialog.body',
-          messageOptions: { wifiName },
-          okKey: 'generic.forget',
-        })
-        if (!decision || !wifi) {
```
Comment (tyler-whitman) [inline src/features/hotspots/settings/WifiSettings.tsx:56]: So was the main problem that the `removeConfiguredWifi` was getting skipped?

**Review by tyler-whitman — APPROVED** [review]

File: src/features/hotspots/settings/WifiSettings.tsx (hunk 2 above)
Comment (matthewcarlreetz) [reply src/features/hotspots/settings/WifiSettings.tsx:56]: it was just returning early because `wifi` was empty
