### PR TITLE
Fix hotspot transfer submission and detail view.

### LINKED ISSUE #303: Mock pending transaction for transfer hotspot is empty/incorrect
image

Notice that the Hotspot name is wrong.. buyer and seller are empty. 

Once the transfer confirms, it looks correct.
image

### PR DESCRIPTION
**Pull request by matthewcarlreetz**
Fixes #303

### CODE REVIEW

File: src/features/wallet/root/ActivityDetails/HotspotTransaction.tsx [hunk 1]
```diff
@@ -14,29 +14,58 @@ import Text from '../../../../components/Text'
...
 
+const isAssert = (
+  arg: AnyTransaction | PendingTransaction,
+): arg is AssertLocationV1 => 'lat' in arg
+const isGateway = (
+  arg: AnyTransaction | PendingTransaction,
+): arg is AddGatewayV1 => 'gateway' in arg
+const isTransfer = (
+  arg: AnyTransaction | PendingTransaction,
+): arg is TransferHotspotV1 => 'seller' in arg
```
Comment (tyler-whitman) [inline src/features/wallet/root/ActivityDetails/HotspotTransaction.tsx:25]: Hmm this kinda sucks there isn't a better way to tell which transaction is which. Maybe we should check for `amountToSeller` as thats pretty specific to transfers. Would hate for some other transaction to have `seller` in it

File: src/features/wallet/root/ActivityDetails/HotspotTransaction.tsx [hunk 2]
```diff
@@ -14,29 +14,58 @@ import Text from '../../../../components/Text'
...
+
 type Props = { item: AnyTransaction | PendingTransaction; address: string }
 const HotspotTransaction = ({ item, address }: Props) => {
+  console.log(JSON.stringify(item, null, 2))
```
Comment (tyler-whitman) [inline src/features/wallet/root/ActivityDetails/HotspotTransaction.tsx:29]: Lets remove this log before we merge

File: src/utils/transactions.ts [hunk 3]
```diff
@@ -92,15 +92,14 @@ export const makeSellerTransferHotspotTxn = async (
...
-    throw new Error('missing buyer speculativeNonce')
+  if (!buyerAccount) throw new Error('missing buyer account')
 
   const transferHotspotTxn = new TransferHotspotV1({
     gateway,
     seller,
     buyer,
     amountToSeller,
-    buyerNonce: buyerAccount.speculativeNonce + 1,
+    buyerNonce: (buyerAccount.speculativeNonce || 0) + 1,
```
Comment (tyler-whitman) [inline src/utils/transactions.ts:102]: Thanks for fixing this, I think its the reason people transfers are failing. If the buyers account is new it would fail.

File: src/utils/transactions.ts [hunk 4]
```diff
@@ -92,15 +92,14 @@ export const makeSellerTransferHotspotTxn = async (
   const buyer = Address.fromB58(buyerB58)
   const buyerAccount = await getAccount(buyerB58)
 
-  if (!buyerAccount || !buyerAccount.speculativeNonce)
-    throw new Error('missing buyer speculativeNonce')
+  if (!buyerAccount) throw new Error('missing buyer account')
```
Comment (tyler-whitman) [inline src/utils/transactions.ts:95]: Im going to add one more check to this to show an alert if the code fails here

File: src/features/wallet/root/ActivityDetails/HotspotTransaction.tsx (hunk 1 above)
Comment (tyler-whitman) [reply src/features/wallet/root/ActivityDetails/HotspotTransaction.tsx:25]: Actually now im thinking maybe seller is better, because `amountToSeller` is also optional. So ill leave it

**Review by tyler-whitman — APPROVED** [review]

**Review by allenan — APPROVED** [review]
lots of good fixes in here 👍
