### PR TITLE
Challenge data for hotspot details

### LINKED ISSUE #141: Update Hotspot Details: Challenge Data
For launch, we should remove the dummy data in the Challenge Past/Fail pod and use real data. Blocked by https://github.com/helium/blockchain-http/issues/172

The first pass will use the total number of challenges the hotspots was either a witness, challenger, or challengee in.

### PR DESCRIPTION
**Pull request by tyler-whitman**
closes #141

### CODE REVIEW

File: src/store/hotspotDetails/hotspotDetailsSlice.ts [hunk 1]
```diff
@@ -72,66 +33,135 @@ const fillMissingHourlyValues = (array: Sum[]) => {
...
+    (a, b) => ({ sum: a.sum + b.sum } as any),
+  )
+  return {
+    challengeSums,
+    challengeSum: totalSum.sum,
+    challengeChange: calculatePercentChange(totalSum.sum, prevSum.sum),
+  }
+}
+
+export const fetchHotspotDetails = createAsyncThunk(
```
Comment (tyler-whitman) [inline src/store/hotspotDetails/hotspotDetailsSlice.ts:105]: Decided to combine them all into one call since we were calling them all at the same time anyway. Now we can load them in parallel

File: src/store/hotspotDetails/hotspotDetailsSlice.ts [hunk 2]
```diff
@@ -72,66 +33,135 @@ const fillMissingHourlyValues = (array: Sum[]) => {
...
+    const data = await Promise.all([
+      getHotspotDetails(params.address),
+      getHotspotRewardsSum(params.address, params.numDays),
+      getHotspotRewardsSum(params.address, params.numDays, endDate),
+      getHotspotRewards(params.address, params.numDays),
+      getHotspotWitnesses(params.address),
+      fetchHotspotWitnessSums(params, startDate, endDate, bucket),
+      fetchHotspotChallengeSums(params, startDate, endDate, bucket),
+    ])
+    // TODO: handle failures
```
Comment (tyler-whitman) [inline src/store/hotspotDetails/hotspotDetailsSlice.ts:121]: Don't know what we want to do about failures? Right now it will just show no data and if you change the timeline it would try to load again

File: src/features/hotspots/details/HotspotDetails.tsx [hunk 3]
```diff
@@ -234,13 +210,23 @@ const HotspotDetails = () => {
...
         <HotspotDetailChart
           title={t('hotspot_details.challenge_title')}
-          percentage={78}
+          subTitle={t('hotspot_details.challenge_sub_title')}
+          number={challengeSum?.toFixed(0)}
+          change={challengeChange}
           color={colors.purpleMain}
-          data={data[2]}
+          data={
+            challengeSums?.map((w) => ({
```
Comment (matthewcarlreetz) [inline src/features/hotspots/details/HotspotDetails.tsx:222]: I'd recommend breaking this out into a `useMemo`

**Review by matthewcarlreetz — APPROVED** [review]

File: src/features/hotspots/details/HotspotDetails.tsx (hunk 3 above)
Comment (tyler-whitman) [reply src/features/hotspots/details/HotspotDetails.tsx:222]: Updated
