### PR TITLE
fix qr scan on second attempt

### LINKED ISSUE #1111: Android - Payment QR code only recognized first payment, second time it's not.
With a Samsung S9 the first time a QR Code for payment is presented, it is recognized and automatically fills the payment details. When after that payment a second QR Code is presented it is simply not recognized anymore, the app needs to be restarted and it works again.

**To Reproduce**

1. Go to 'Send HNT.'
2. Click on QR Code next to recipient
3. Scan QR Code
4. It should work and fill in the details in the Send HNT Payment
5. Pay
6. Go to 'Send HNT.'
7. Click on QR Code next to recipient
8. Scan QR Code
9. QR Code is not recognized anymore..

**Expected behavior**
Every time a valid  payment QR code is scanned it should recognize it and fill in the details in the Send HNT Screen

**Screenshots**
n/a
**Smartphone (please complete the following information):**

- Device: Samsung S9
- OS: Android 10
- App  3.8.3

**Additional context**

### PR DESCRIPTION
**Pull request by tyler-whitman**
closes #1111

### CODE REVIEW

File: src/features/wallet/scan/ScanView.tsx [hunk 1]
```diff
@@ -6,6 +6,7 @@ import { useTranslation } from 'react-i18next'
 import { useSelector } from 'react-redux'
 import { BarCodeScanner, BarCodeScannerResult } from 'expo-barcode-scanner'
```
Comment (matthewcarlreetz) [inline src/features/wallet/scan/ScanView.tsx:7]: Can we remove `expo-barcode-scanner` entirely now? I believe we get everything we need from 
`import { Camera, BarCodeScanningResult } from 'expo-camera'`

**Review by matthewcarlreetz — APPROVED** [review]

File: src/features/wallet/scan/ScanView.tsx (hunk 1 above)
Comment (tyler-whitman) [reply src/features/wallet/scan/ScanView.tsx:7]: It looks like we still need it for the type to pass to https://docs.expo.dev/versions/latest/sdk/camera/#barcodescannersettings
