### PR TITLE
check if payment address is a hotspot or validator address

### LINKED ISSUE #935: Add warning if payment being sent to new or hotspot/validator address
To help prevent sending HNT to an incorrect wallet, detect if the payee does not exist or is a hotspot/validator address, and show a warning/confirmation screen.  Suggested text:

"The Payee address does not yet exist, or looks like a Hotspot.  Do you want to proceed?"

### PR DESCRIPTION
**Pull request by tyler-whitman**
closes #935

### CODE REVIEW

File: src/features/wallet/send/SendDetailsForm.tsx [hunk 1]
```diff
@@ -200,16 +236,28 @@ const SendDetailsForm = ({
...
+            }
             onScanPress={onScanPress}
           />
         }
-        footer={<AddressAliasFooter addressAlias={addressAlias} />}
+        footer={
+          <Box>
+            <AddressAliasFooter addressAlias={addressAlias} />
+            {isHotspotAddress && (
+              <Text color="redMain">{t('send.not_valid_address')}</Text>
```
Comment (matthewcarlreetz) [inline src/features/wallet/send/SendDetailsForm.tsx:257]: There's a few `<Text>` components in this file that are missing the `variant` attribute. This causes them to use the system font. I think we want either "body2"  or "body2Mono" as the variant.

**Review by matthewcarlreetz — CHANGES_REQUESTED** [review]

**Review by matthewcarlreetz — APPROVED** [review]
