### PR TITLE
Bugfix/365 ble android

### LINKED ISSUE #365: Fix "Operation was cancelled" error
On Android after canceling the ble WiFi connect subscription this error is thrown. It's a non-issue, but it's clogging up the logs in Sentry. Need to find a way to ignore this error.

I thought I had it handled on lines 255-269 of
`src/utils/useHotspot.ts`, but apparently, it's not working.

### PR DESCRIPTION
**Pull request by matthewcarlreetz**
closes #365 

Removes the need to scan twice on android when ble is off
Removes error log when wifi subscription is removed on android

### CODE REVIEW

File: src/utils/bluetooth/useBluetooth.tsx [hunk 1]
```diff
@@ -35,9 +35,7 @@ const useBluetooth = () => {
 
   const getState = async () => getBleManager().state()
 
-  const enable = async () => {
-    getBleManager().enable()
-  }
+  const enable = async () => getBleManager().enable()
```
Comment (matthewcarlreetz) [inline src/utils/bluetooth/useBluetooth.tsx:38]: this is being awaited, but the function wasn't returning the promise 🤦

Comment (tyler-whitman) [reply src/utils/bluetooth/useBluetooth.tsx:38]: Ah good catch

**Review by tyler-whitman — APPROVED** [review]
